DROP TABLE if EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(75) NOT NULL,
  password VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
)

DROP TABLE IF EXISTS posts

CREATE TABLE posts (
  id SERIAL PRIMARY KEY AUTOINCREMENT,
  post_content VARCHAR(75) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  user_id SERIAL NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
) 